export {}
// Defines all locations on a user can select from when reporting where an item was found
// export const LOCATION_OPTIONS =
//     [
//         // Note: the list is automatically sorted alphabetically when displayed to the user
//         `Main Green`,
//         `Sciences Library (Sci Li)`,
//         `Metcalf`,
//         `Wayland`,
//     ]
//     // TODO: Add more locations!
// // `TODO: Use this link to fill in: https://en.wikipedia.org/wiki/List_of_Brown_University_buildings`


export const LOCATION_OPTIONS = [
    {enumString:'FIFTHAVE500', label: '5th Ave 500'},
    {enumString:'ALUMNAEHALL', label: 'Alumnae Hall'},
    {enumString:'ANDREWSHALL', label: 'Andrews Hall'},
    {enumString:'ANDREWSHOUSE', label: 'Andrews House'},
    {enumString:'ANDREWSMEMORIALBUILDING', label: 'Andrews Memorial Building'},
    {enumString:'ANGELLST127', label: 'Angell St 127'},
    {enumString:'ANGELLST129', label: 'Angell St 129'},
    {enumString:'ANGELLST164', label: 'Angell St 164'},
    {enumString:'ANGELLST169', label: 'Angell St 169'},
    {enumString:'ANGELLST195', label: 'Angell St 195'},
    {enumString:'ANNMARYBROWNMEMORIALLIBRARY', label: 'Annmary Brown Memorial Library'},
    {enumString:'ARCHIBALDBRONSONKEENEYQUAD', label: 'Archibald-Bronson: Keeney Quad'},
    {enumString:'ARNOLDLAB', label: 'Arnold Lab'},
    {enumString:'BARBOURHALL', label: 'Barbour Hall'},
    {enumString:'BARUSANDHOLLEY', label: 'Barus & Holley'},
    {enumString:'BARUSBUILDING', label: 'Barus Building'},
    {enumString:'BENEVOLENTST005', label: 'Benevolent St 005'},
    {enumString:'BENEVOLENTST020', label: 'Benevolent St 020'},
    {enumString:'BENEVOLENTST022', label: 'Benevolent St 022'},
    {enumString:'BENEVOLENTST026', label: 'Benevolent St 026'},
    {enumString:'BENEVOLENTST074080', label: 'Benevolent St 074-080'},
    {enumString:'BENEVOLENTST083085', label: 'Benevolent St 083-085'},
    {enumString:'BENEVOLENTST084', label: 'Benevolent St 084'},
    {enumString:'BENEVOLENTST086', label: 'Benevolent St 086'},
    {enumString:'BENEVOLENTST088', label: 'Benevolent St 088'},
    {enumString:'BENEVOLENTST093', label: 'Benevolent St 093'},
    {enumString:'BENONICOOKEHOUSE', label: 'Benoni Cooke House'},
    {enumString:'BIOMEDACF', label: 'Bio-Med ACF'},
    {enumString:'BIOMEDCTR', label: 'Bio-Med Ctr'},
    {enumString:'BIOMEDGRIMSHAWGUDEWICZ', label: 'Bio-Med Grimshaw-Gudewicz'},
    {enumString:'BLISTEINHOUSE', label: 'Blistein House'},
    {enumString:'BOWENST219', label: 'Bowen St 219'},
    {enumString:'BOWENST244', label: 'Bowen St 244'},
    {enumString:'BOWENST247', label: 'Bowen St 247'},
    {enumString:'BOWENST251', label: 'Bowen St 251'},
    {enumString:'BROADWAY233', label: 'Broadway 233'},
    {enumString:'BROOKST245247', label: 'Brook St 245-247'},
    {enumString:'BROOKST250', label: 'Brook St 250'},
    {enumString:'BROOKST281283', label: 'Brook St 281-283'},
    {enumString:'BROOKST287', label: 'Brook St 287'},
    {enumString:'BROOKST291', label: 'Brook St 291'},
    {enumString:'BROOKST456', label: 'Brook St 456'},
    {enumString:'BROWNST0685', label: 'Brown St 068.5'},
    {enumString:'BROWNST070', label: 'Brown St 070'},
    {enumString:'BROWNST111', label: 'Brown St 111'},
    {enumString:'BROWNST131133', label: 'Brown St 131-133'},
    {enumString:'BROWNSTADIUM', label: 'Brown Stadium'},
    {enumString:'BUXTONHOUSEWRISTONQUAD', label: 'Buxton House: Wriston Quad'},
    {enumString:'CARRIETOWER', label: 'Carrie Tower'},
    {enumString:'CASWELLHALL', label: 'Caswell Hall'},
    {enumString:'CENTRALHEATPLANT', label: 'Central Heat Plant'},
    {enumString:'CHAMPLINPEMBROKEQUAD', label: 'Champlin: Pembroke Quad'},
    {enumString:'CHAPINHOUSEWRISTONQUAD', label: 'Chapin House: Wriston Quad'},
    {enumString:'CHARLESFIELDST059', label: 'Charlesfield St 059'},
    {enumString:'CHARLESFIELDST066068', label: 'Charlesfield St 066-068'},
    {enumString:'CHARLESFIELDST070072', label: 'Charlesfield St 070-072'},
    {enumString:'CHARLESFIELDST071073', label: 'Charlesfield St 071-073'},
    {enumString:'CHARLESFIELDST075', label: 'Charlesfield St 075'},
    {enumString:'CHARLESFIELDST108110', label: 'Charlesfield St 108-110'},
    {enumString:'CHURCHILLHOUSE', label: 'Churchill House'},
    {enumString:'CLAVERICKST055', label: 'Claverick St 055'},
    {enumString:'COOKEST037', label: 'Cooke St 037'},
    {enumString:'CORLISSBRACKETT', label: 'Corliss-Brackett'},
    {enumString:'CUSHINGST084086', label: 'Cushing St 084-086'},
    {enumString:'CUSHINGST154', label: 'Cushing St 154'},
    {enumString:'CUSHINGST166', label: 'Cushing St 166'},
    {enumString:'DAVOLSQ001', label: 'Davol Sq 001'},
    {enumString:'DAVOLSQ003', label: 'Davol Sq 003'},
    {enumString:'DIMANHOUSEWRISTONQUAD', label: 'Diman House: Wriston Quad'},
    {enumString:'DYERHOUSE', label: 'Dyer House'},
    {enumString:'DYERST200', label: 'Dyer St 200'},
    {enumString:'DYERST225', label: 'Dyer St 225'},
    {enumString:'EDDYST339', label: 'Eddy St 339'},
    {enumString:'EDDYST349', label: 'Eddy St 349'},
    {enumString:'ELMST043', label: 'Elm St 043'},
    {enumString:'ELMST110', label: 'Elm St 110'},
    {enumString:'EMERYPEMBROKEQUAD', label: 'Emery: Pembroke Quad'},
    {enumString:'ENGINEERINGRESEARCHCENTER', label: 'Engineering Research Center'},
    {enumString:'EUCLIDAVE001', label: 'Euclid Ave 001'},
    {enumString:'EVERETTPOLANDKEENEYQUAD', label: 'Everett-Poland: Keeney Quad'},
    {enumString:'FACULTYCLUB', label: 'Faculty Club'},
    {enumString:'FAUNCEHOUSE', label: 'Student/Campus Center: Faunce House'},
    {enumString:'FEINSTEIN', label: 'Feinstein'},
    {enumString:'FIERINGHOUSE', label: 'Fiering House'},
    {enumString:'FONESALLEY008', label: 'Fones Alley 008'},
    {enumString:'FOXPOINTDAYCARECTR', label: 'Fox Point Day Care Ctr'},
    {enumString:'FRIEDMANHALL', label: 'Friedman Hall'},
    {enumString:'GARDNERHOUSE', label: 'Gardner House'},
    {enumString:'GEOCHEMBLDG', label: 'Geo-Chem Building'},
    {enumString:'GEORGEST025', label: 'George St 025'},
    {enumString:'GEORGEST067', label: 'George St 067'},
    {enumString:'GEORGEST155', label: 'George St 155'},
    {enumString:'GEORGEST180', label: 'George St 180'},
    {enumString:'GEORGEST182', label: 'George St 182'},
    {enumString:'GERARDHOUSESAMUELN', label: 'Gerard House, Samuel N.'},
    {enumString:'GIDDINGSHOUSE', label: 'Giddings House'},
    {enumString:'GODDARDHOUSEWRISTONQUAD', label: 'Goddard House: Wriston Quad'},
    {enumString:'GRADUATECTRA', label: 'Graduate Center A'},
    {enumString:'GRADUATECTRB', label: 'Graduate Center B'},
    {enumString:'GRADUATECTRC', label: 'Graduate Center C'},
    {enumString:'GRADUATECTRD', label: 'Graduate Center D'},
    {enumString:'GRADUATECTRE', label: 'Graduate Center E'},
    {enumString:'GRANOFFCTRFORTHECREATIVEARTS', label: 'Granoff Ctr For The Creative Arts'},
    {enumString:'GRANTFULTON', label: 'Grant Fulton'},
    {enumString:'HAFFENREFFERBARN', label: 'Haffenreffer Barn'},
    {enumString:'HAFFENREFFERCARETAKERHOUSE', label: 'Haffenreffer Caretaker House'},
    {enumString:'HAFFENREFFERMUSEUMCOLLECTIONSRES', label: 'Haffenreffer Museum Collections Res'},
    {enumString:'HAFFENREFFEROUTINGRESERVATIONFAC', label: 'Haffenreffer Outing Reservation Fac'},
    {enumString:'HARKNESSHOUSEWRISTONQUAD', label: 'Harkness House: Wriston Quad'},
    {enumString:'HEGEMANHALL', label: 'Hegeman Hall'},
    {enumString:'HEMISPHEREBLDG', label: 'Hemisphere Building'},
    {enumString:'HILLELHOUSE', label: 'Hillel House'},
    {enumString:'HIRSCHFELDHOUSE', label: 'Hirschfeld House'},
    {enumString:'HOPECOLLEGE', label: 'Hope College'},
    {enumString:'HOPEST170', label: 'Hope St 170'},
    {enumString:'HOPEST190', label: 'Hope St 190'},
    {enumString:'HOPPINTHOMASPHOUSE', label: 'Hoppin (Thomas P.) House'},
    {enumString:'HORACEMANNHOUSE', label: 'Horace Mann House'},
    {enumString:'JAMESONMEADKEENEYQUAD', label: 'Jameson-Mead: Keeney Quad'},
    {enumString:'JOHNCARTERBROWNLIBRARY', label: 'John Carter Brown Library'},
    {enumString:'JOHNHAYLIBRARY', label: 'John Hay Library'},
    {enumString:'JOHNST050', label: 'John St 050'},
    {enumString:'KASSAREDWARDWHOUSE', label: 'Kassar (Edward W.) House'},
    {enumString:'KINGHOUSE', label: 'King House'},
    {enumString:'LADDOBSERVATORY', label: 'Ladd Observatory'},
    {enumString:'LINCOLNFIELDBUILDING', label: 'Lincoln Field Building'},
    {enumString:'LIPPITTHOUSE', label: 'Lippitt House'},
    {enumString:'LISTALBERTANDVERAARTBUILDING', label: 'List (Albert & Vera) Art Building'},
    {enumString:'LITTLEFIELDHALL', label: 'Littlefield Hall'},
    {enumString:'LLOYDAVE165167', label: 'Lloyd Ave 165-167'},
    {enumString:'LYMANHALL', label: 'Lyman Hall'},
    {enumString:'MACFARLANEHOUSE', label: 'MacFarlane House'},
    {enumString:'MACHADOANTONIOHOUSE', label: 'Machado (Antonio) House'},
    {enumString:'MACMILLANHALL', label: 'MacMillan Hall'},
    {enumString:'MADDOCKALUMNICENTER', label: 'Maddock Alumni Center'},
    {enumString:'MANNINGHALL', label: 'Manning Hall'},
    {enumString:'MARCYHOUSEWRISTONQUAD', label: 'Marcy House: Wriston Quad'},
    {enumString:'MARSTONBOATHOUSE', label: 'Marston Boathouse'},
    {enumString:'MARSTONHALL', label: 'Marston Hall'},
    {enumString:'MAXCYHALL', label: 'Maxcy Hall'},
    {enumString:'MEDICALRESEARCHLAB', label: 'Medical Research Lab'},
    {enumString:'MEEHANAUDITORIUM', label: 'Meehan Auditorium'},
    {enumString:'MEETINGST205', label: 'Meeting St 205'},
    {enumString:'MEETINGST242', label: 'Meeting St 242'},
    {enumString:'MEIKLEJOHNHOUSE', label: 'Meiklejohn House'},
    {enumString:'MENCOFFHALL', label: 'Mencoff Hall'},
    {enumString:'METCALFHALL', label: 'Metcalf Hall'},
    {enumString:'METCALFRESEARCHBUILDING', label: 'Metcalf Research Building'},
    {enumString:'MILLERHALL', label: 'Miller Hall'},
    {enumString:'MINDENHALL', label: 'Minden Hall'},
    {enumString:'MONTGOMERYST601', label: 'Montgomery St 601'},
    {enumString:'MORRISONGERARDSTUDIO', label: 'Morrison-Gerard Studio'},
    {enumString:'MORRISSHALLPEMBROKEQUAD', label: 'Morriss Hall: Pembroke Quad'},
    {enumString:'NELSONFITNESSCENTER', label: 'Nelson Fitness Center'},
    {enumString:'NEWPEMBROKENO1', label: 'New Pembroke No. 1'},
    {enumString:'NEWPEMBROKENO2', label: 'New Pembroke No. 2'},
    {enumString:'NEWPEMBROKENO3', label: 'New Pembroke No. 3'},
    {enumString:'NEWPEMBROKENO4', label: 'New Pembroke No. 4'},
    {enumString:'NICHOLSONHOUSE', label: 'Nicholson House'},
    {enumString:'NIGHTINGALEBROWNHOUSE', label: 'Nightingale-Brown House'},
    {enumString:'NORWOODHOUSE', label: 'Norwood House'},
    {enumString:'OLIVEST020', label: 'Olive St 020'},
    {enumString:'OLNEYHOUSEWRISTONQUAD', label: 'Olney House: Wriston Quad'},
    {enumString:'OLNEYMARGOLIESATHLETICCENTER', label: 'Olney-Margolies Athletic Center'},
    {enumString:'ORWIGMUSICHALL', label: 'Orwig Music Hall'},
    {enumString:'PAGEROBINSONHALL', label: 'Page-Robinson Hall'},
    {enumString:'PARKLANE010', label: 'Park Lane 010'},
    {enumString:'PARTRIDGEHALLANDANNEX', label: 'Partridge Hall & Annex'},
    {enumString:'PEMBROKEFIELDHOUSE', label: 'Pembroke Field House'},
    {enumString:'PEMBROKEHALL', label: 'Pembroke Hall'},
    {enumString:'PERKINSHALL', label: 'Perkins Hall'},
    {enumString:'PETERGREENHOUSE', label: 'Peter Green House'},
    {enumString:'PIZZITOLA', label: 'Pizzitola'},
    {enumString:'POWERST089', label: 'Power St 089'},
    {enumString:'POWERSTPARKINGGARAGE', label: 'Power St Parking Garage'},
    {enumString:'PRESIDENTSHOUSE', label: 'President\'s House'},
    {enumString:'PRINCEENGINEERINGLAB', label: 'Prince Engineering Lab'},
    {enumString:'PROSPECTHOUSE', label: 'Prospect House'},
    {enumString:'RHODEISLANDHALL', label: 'Rhode Island Hall'},
    {enumString:'RICHMONDST196', label: 'Richmond St 196'},
    {enumString:'RICHMONDST222', label: 'Richmond St 222'},
    {enumString:'RICHMONDST222PARKINGGARAGE', label: 'Richmond St 222 Parking Garage'},
    {enumString:'RICHMONDST233', label: 'Richmond St 233'},
    {enumString:'ROBINSONHALL', label: 'Robinson Hall'},
    {enumString:'ROCHAMBEAUHOUSE', label: 'Rochambeau House'},
    {enumString:'ROCKEFELLERJOHNDJRLIBRARY', label: 'Rockefeller (John D., Jr.) Library'},
    {enumString:'SALOMONCTRFORTEACHING', label: 'Salomon Ctr For Teaching'},
    {enumString:'SAYLESHALL', label: 'Sayles Hall'},
    {enumString:'SCIENCESLIBRARY', label: 'Sciences Library (Sci Li)'},
    {enumString:'SEARSHOUSEWRISTONQUAD', label: 'Sears House: Wriston Quad'},
    {enumString:'SHARPEHOUSE', label: 'Sharpe House'},
    {enumString:'SHARPEREFECTORY', label: 'Sharpe Refectory (Ratty)'},
    {enumString:'SHIPST026', label: 'Ship St 026'},
    {enumString:'SHIPST070', label: 'Ship St 070'},
    {enumString:'SHIRLEYMILLERHOUSE', label: 'Shirley Miller House'},
    {enumString:'SIDNEYEFRANKHALLLIFESCIENCES', label: 'Sidney E. Frank Hall Life Sciences'},
    {enumString:'SLATERHALL', label: 'Slater Hall'},
    {enumString:'SMITHBUONANNOHALL', label: 'Smith-Buonanno Hall'},
    {enumString:'SOUTHMAINST121', label: 'South Main St 121'},
    {enumString:'SOUTHSTREETLANDING', label: 'South Street Landing'},
    {enumString:'STEINERTCENTER', label: 'Steinert Center'},
    {enumString:'STEPHENROBERTHALL', label: 'Stephen Robert Hall'},
    {enumString:'STIMSONAVE002', label: 'Stimson Ave 002'},
    {enumString:'TFGREENHALL', label: 'T.F. Green Hall'},
    {enumString:'THAYERST135', label: 'Thayer St 135'},
    {enumString:'THAYERST271', label: 'Thayer St 271'},
    {enumString:'THAYERST272', label: 'Thayer St 272'},
    {enumString:'THAYERST307', label: 'Thayer St 307'},
    {enumString:'THAYERST315', label: 'Thayer St 315'},
    {enumString:'UNIVERSITYHALL', label: 'University Hall'},
    {enumString:'URBANENVIRONMENTALLAB', label: 'Urban Environmental Lab'},
    {enumString:'VARTANGREGORIANQUADA', label: 'Vartan Gregorian Quad A'},
    {enumString:'VARTANGREGORIANQUADB', label: 'Vartan Gregorian Quad B'},
    {enumString:'VERNEYWOOLLEYHALLPEMBROKEQUAD', label: 'Verney-Woolley Hall: Pembroke Quad'},
    {enumString:'WALTERHALL', label: 'Walter Hall'},
    {enumString:'WATERMANST070', label: 'Waterman St 070'},
    {enumString:'WATERMANST085', label: 'Waterman St 085'},
    {enumString:'WATERMANST086', label: 'Waterman St 086'},
    {enumString:'WATERMANST094', label: 'Waterman St 094'},
    {enumString:'WATERMANST125127', label: 'Waterman St 125-127'},
    {enumString:'WATERMANST129', label: 'Waterman St 129'},
    {enumString:'WATERMANST131', label: 'Waterman St 131'},
    {enumString:'WATERMANST133', label: 'Waterman St 133'},
    {enumString:'WATERMANST137', label: 'Waterman St 137'},
    {enumString:'WATSONCENTERFORINFORMATIONTECH', label: 'Watson Center For Information Tech (CIT)'},
    {enumString:'WATSONINSTITUTE', label: 'Watson Institute'},
    {enumString:'WAYLANDHOUSEWRISTONQUAD', label: 'Wayland House: Wriston Quad'},
    {enumString:'WESTHOUSE', label: 'West House'},
    {enumString:'WILBOURHALL', label: 'Wilbour Hall'},
    {enumString:'WOOLLEYHALLPEMBROKEQUAD', label: 'Woolley Hall: Pembroke Quad'},
    {enumString:'YOUNGORCHARDAVE002', label: 'Young Orchard Ave 002'},
    {enumString:'YOUNGORCHARDAVE004', label: 'Young Orchard Ave 004'},
    {enumString:'YOUNGORCHARDAVE010', label: 'Young Orchard Ave 010'},
    // Manually added
    {enumString:'MAINGREEN', label: 'Main Green'},
    {enumString:'QUIETGREEN', label: 'Quiet Green'},
    {enumString:'SIMMONSQUD', label: 'Ruth J. Simmons Quad'},
    {enumString:'HUGHESCOURT', label: 'Hughes Court'},
    {enumString:'PEMBROKEQUAD', label: 'Pembroke Quad'},
    {enumString:'JOSIAHS', label: 'Josiah\'s (Jo\'s/Jos/Joes)'},
    {enumString:'BLUEROOM', label: 'Blue Room Cafe'},
    {enumString:'OTHER', label: 'Other'},
]